name: Delivery

on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [master]
  release:
    # Note: a current limitation is that when a release is edited after publication, then the Docker tags are not automatically updated.
    types: [published]
  schedule:
    # Run every monday on 9:00 in the morning (UTC).
    - cron: '0 9 * * 1'

permissions:
  contents: write
  packages: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      is-head-main: ${{ steps.is-head-main.outcome == 'success' }}
      is-latest-release: ${{ steps.is-latest-release.outcome == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check whether this event is the HEAD of main
        continue-on-error: true
        id: is-head-main
        run: git rev-parse HEAD | grep -x ${{ github.sha }}
        shell: bash

      - name: Check whether the release is latest
        continue-on-error: true
        id: is-latest-release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release view --json tagName --jq .tagName | grep -x ${{ github.event.release.tag_name }}
        shell: bash

  publish-docker-image:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=edge,enable=${{ needs.prepare.outputs.is-head-main == 'true' }}
            type=raw,value=latest,enable=${{ needs.prepare.outputs.is-latest-release == 'true' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container and export to local Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: local/yivitube:scan
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan Image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: local/yivitube:scan
          only-fixed: true
          fail-build: true
          severity-cutoff: high
          output-format: sarif

      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() }}
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Push image to GitHub Container Registry
        uses: docker/build-push-action@v5
        if: ${{ github.event_name == 'release' || github.event_name == 'push' }}
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
